import type { DocBridgeConfigV1 } from '../config/schema.js'
import type { KnowledgeEntry } from '../schemas/doc-bridge-index.js'
import { isProjectedEntry } from './project-corpus.js'

const routePath = (path: string, pathPrefix: string | undefined): string => {
  const normalizedPath = path.replaceAll('\\', '/').replace(/\.(?:md|mdx)$/, '')
  const normalizedPrefix = pathPrefix?.replaceAll('\\', '/').replace(/\/$/, '')
  const relativePath = normalizedPrefix && normalizedPath.startsWith(`${normalizedPrefix}/`)
    ? normalizedPath.slice(normalizedPrefix.length + 1)
    : normalizedPath
  return relativePath.replace(/^\/+/, '')
}

export const knowledgeUrl = (
  path: string,
  options: { readonly urlPrefix?: string | undefined; readonly pathPrefix?: string | undefined } = {},
): string => {
  const relativePath = routePath(path, options.pathPrefix)
  if (!options.urlPrefix) return path
  const base = options.urlPrefix.endsWith('/') ? options.urlPrefix : `${options.urlPrefix}/`
  return new URL(relativePath, base).toString()
}

export const renderLlmsTxt = (
  config: DocBridgeConfigV1,
  knowledge: readonly KnowledgeEntry[],
  projectName: string,
): string => {
  const preamble =
    config.index?.llmsTxt?.preamble ??
    `# ${projectName}\n\n> Agent-readable documentation index generated by ak-docs (@agentskit/doc-bridge).\n`

  /*
   * llms.txt is a reading order, not an inventory. The index also carries every document and
   * module the repository projects into it for retrieval; listing those here would bury the
   * curated entry points an agent is meant to start from. The filter lives in the renderer so
   * every caller — the builder and the conformance profile that re-renders to check freshness —
   * agrees on what the file contains.
   */
  const lines = knowledge
    .filter((entry) => !isProjectedEntry(entry))
    .slice(0, 500)
    .map((entry) => {
      const desc = entry.description ? `: ${entry.description}` : ''
      const url = knowledgeUrl(entry.path, config.index?.llmsTxt)
      return `- [${entry.title}](${url})${desc}`
    })

  return `${preamble.trim()}\n\n## Knowledge\n\n${lines.join('\n')}\n`
}
